warmachine028/uemcrp

- CNAME
- client/src/components/Auth/index.jsx
- **I Sohel have worked for <#6>**
- **My pull request closes <#6>**
---
> PlaceHolder text

- client/src/components/Auth/index.jsx
- **I Pritam Kundu have worked for #6**
- **My pull request closes #6**
---
> Added Fix for Faulty PR #14

- client/src/components/Auth/index.jsx
- **I Sohel have worked for #18**
- **My pull request closes #18 **
---
> added fixes for  #18

- client/src/App/index.jsx
- client/src/components/studentModules/Attendance/index.jsx
- client/src/components/studentModules/OrganisationalCalander/index.jsx
- client/src/components/studentModules/Payduefees/index.jsx
- client/src/components/studentModules/Paymentdetails/index.jsx
- client/src/components/studentModules/UnitTestDetails/index.jsx
- client/src/components/studentModules/UniversityMarkingSystem/index.jsx
- client/src/components/studentModules/UpdateInfo/index.jsx
- client/src/components/studentModules/index.js
- **I Sohel have worked for #19**
- **My pull request closes #19**
---
> added fixes for #19

- README.md
- **I Pritam Kundu have worked for #5**
- **My pull request closes #5**
---
> Added Auth Design in Figma for fixes in #5

- README.md
- **I Rashmi Subhash have worked for #34**
- **My pull request closes #34**
---
> updated readme file according to the issue no 34

- client/src/components/Navbar/styles.js
- client/src/components/studentModules/AdmitCard/Card/index.jsx
- client/src/components/studentModules/AdmitCard/Card/styles.js
- client/src/components/studentModules/AdmitCard/styles.js
- **I Zuzexx have worked for #33**
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes #33**
- 1. admitCardMobile
- 2. admitCardIphone   
- 3. mobile
---
> Admit cards mobile responsive

- client/src/App/index.jsx
- client/src/components/Auth/index.jsx
- client/src/components/Auth/styles.js
- client/src/components/Form/index.jsx
- client/src/components/Form/styles.js
- client/src/components/Input/index.jsx
- client/src/components/studentModules/Attendance/Ratings/index.jsx
- client/src/components/studentModules/Attendance/Ratings/styles.js
- client/src/components/studentModules/Attendance/index.jsx
- client/src/components/studentModules/Attendance/styles.js
- **I Pritam Kundu have worked for #42**
- **My pull request closes #42**
- Attendance Form
- Attendance Form with errors
- Feedback Form
- When the attendance code is not found
---
> Attendance Module 📇 #42

- client/public/manifest.json
- client/src/App/index.jsx
- client/src/components/Auth/index.jsx
- client/src/components/Navbar/styles.js
- client/src/components/studentModules/AdmitCard/index.jsx
- client/src/components/studentModules/AdmitCard/styles.js
- client/src/components/studentModules/Attendance/index.jsx
- client/src/components/studentModules/ChangePassword/index.jsx
- client/src/components/studentModules/ChangePassword/styles.js
- **I Pritam Kundu have worked for #28, #42, #33**
- **My pull request closes #28**
| Change Password | Admit Cards |
|:--:|:--:|
| ![cp](https://user-images.githubusercontent.com/75939390/188208340-554233ee-e95e-4516-afef-edc80c437ec0.png) | ![mobile](https://user-images.githubusercontent.com/75939390/188208151-9de1a9d8-b2f7-4341-9458-b549b0c5db99.png) |
- Attendance
---
> Added Tweaks and Minor fixes for issues ✅📱🏡

- client/src/components/studentModules/Attendance/index.jsx
- Referring to #47 
I've added the Icon inside the Form Component as suggested.
> SaveAs Icon Added to Attendance Form

- client/package-lock.json
- client/package.json
- client/src/components/studentModules/AdmitCard/Card/index.jsx
- client/src/components/studentModules/AdmitCard/index.jsx
- client/src/data/users.js
- server/.gitignore
- **I Pritam Kundu have worked for #54**
- Thanks to [Kendo React](https://www.npmjs.com/package/@progress/kendo-react-pdf) for the day.
- Out of all JStoPDF or reactToPDF libraries this made the work in just a few lines of code.
- **My pull request closes #54**
---
> Added fixes for Download ADMIT Cards 🌟🌟🌟🌟

- client/package-lock.json
- **I Pritam have worked for #62**
- **My pull request closes #62**
N.A.
---
> Added fixed for PR Organizational Calendar #62

- client/src/components/Home/index.jsx
- **I Gabriel Warner have worked for Issue #70**
- **My pull request closes #70 **
BEFORE
AFTER
---
> Removed name field from paper component

- client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
- **I Abhishek have worked for #71**
- **My pull request closes #71**
---
> made responsive calendar

- client/src/components/studentModules/Bills/index.jsx
- client/src/components/studentModules/Bills/styles.js
- **I amanchoudhary18 have worked for #80**
- **My pull request closes #80**
**Here are the pictures of changes that I have made 🔽**
---
> Add : Reset date button

- client/src/App/styles.js
- client/src/components/studentModules/Payduefees/index.jsx
- client/src/components/studentModules/Payduefees/styles.js
- **I Alcadeus0 have worked for #76**
- **My pull request closes #76**
The bug seemed to be from having the styles be applied to the table alongwidth the left align.
---
> Added Responsiveness to PayDues Page

- client/src/components/studentModules/UniversityMarkingSystem/List/styles.js
- client/src/components/studentModules/UniversityMarkingSystem/index.jsx
- client/src/components/studentModules/UniversityMarkingSystem/styles.js
- **I Ritesh Dabral have worked for #81**
- **My pull request closes #81**
---
> UniversityMarkingSystem UI Fixes

- client/src/components/studentModules/Bills/index.jsx
- **I <your name here> have worked for  a bug whare a reset date button wasn't working<issue number>**
- **My pull request closes on 07/10/2022 <hashtag issuenumber>**
---
> bug fixed date reset button working

- .github/workflows/build.yaml
- client/package.json
- #79 Add build test to workflow
- **My pull request closes #79 **
---
> Add build test to workflow

- client/src/components/studentModules/UnitTestDetails/List/index.jsx
- client/src/components/studentModules/UnitTestDetails/List/styles.js
- client/src/components/studentModules/UnitTestDetails/index.jsx
- client/src/components/studentModules/UnitTestDetails/styles.js
- client/src/data/unittest.js
- client/src/data/users.js
- **I Debopriya Dey has worked for #84**
- **My pull request closes #84 **
**Here are the pictures of the changes that I have made 🔽**
* I have added one more field in the existing student object 
* I have assumed that there are two Unit Tests in one Semester and I have created the filter for displaying the unit test result.
---
> Updated the Unit Test Details

- client/src/components/studentModules/Payduefees/index.jsx
- client/src/components/studentModules/Payduefees/styles.js
- **I Harsh Garg have worked for #97**
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes #97**
**Here are the pictures of changes that I have made 🔽**
---
> added smaller font size for mobile view

- client/src/App/styles.js
- client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
- client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/styles.js
- client/src/components/studentModules/OrganisationalCalander/SideBar/index.jsx
- client/src/components/studentModules/OrganisationalCalander/SideBar/styles.js
- client/src/components/studentModules/OrganisationalCalander/index.jsx
- client/src/data/holidays.js
- client/src/index.css
- **I T S Ajeet have worked for #83**
- **My pull request closes #83**
---
> SideBar in calendar organisation

- client/src/components/Dashboard/index.jsx
- client/src/components/Dashboard/styles.js
- **I boltkk95 have worked for #106**
- **My pull request closes #106**
---
> Making the grid items clickable only when hovering over the pictures 

- client/src/components/Dashboard/index.jsx
- client/src/components/Home/index.jsx
- client/src/components/Home/styles.js
- **I boltkk95 have worked for #108 **
- **My pull request closes #108 **
---
> profile pic cursor-some unwanted lines of codes cleared in dashboard

- client/src/components/studentModules/OrganisationalCalander/CustomDateRangePicker/index.jsx
- client/src/components/studentModules/OrganisationalCalander/SideBar/index.jsx
- client/src/components/studentModules/OrganisationalCalander/index.jsx
- **I boltkk95 have worked for #110 **
- **My pull request closes #110 **
---
> calendar enhancement

- client/src/components/studentModules/UnitTestDetails/List/index.jsx
- client/src/components/studentModules/UnitTestDetails/index.jsx
- **I anuj98 have worked for #111**
- **My pull request closes #111**
---
> Fixed the console errors and removed console logs in client app

- client/src/App/index.jsx
- client/src/components/studentModules/UpdateInfo/index.jsx
- client/src/components/studentModules/UpdateInfo/styles.js
- client/src/data/users.js
- **I anuj98 have worked for #114**
- **My pull request closes #114**
Laptop:
Mobile:
---
> Added UI for Update Info page

- client/src/components/Dashboard/styles.js
- **I <Responsiveness Bug in Home> have worked for #115**
- **My pull request closes <#115>**
---
> Fixed responsiveness Bug in Home

- client/src/components/studentModules/Attendance/index.jsx
- client/src/components/studentModules/Attendance/styles.js
there is just one line code added to code and other changes related to prettier extenction
- **My pull request closes <hashtag issuenumber>**
if you got any question to ask feel free to ask, otherwise merge this and close realted issue 
thanks
---
> attendance Error is responsive now
